// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrpsvdbkzgyewhetmebc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhycHN2ZGJremd5ZXdoZXRtZWJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMjYyNzAsImV4cCI6MjA1ODgwMjI3MH0.Eu4vxM-nqf0D3HsEP7N0Iyk1zFD_GJKTr709Jb2qy2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);